# Configuration Variables
MONGODB_URI="localhost:27017"
UMAMI_WEBSITE_ID=""
ADMIN_KEY=""
SUPER_ADMIN_KEY=""
GEMINI_API_KEY=""
NEWS_API_KEY=""
TMDB_API_KEY=""
NASA_API_KEY=""
WEATHER_API_KEY=""
YOUTUBE_API_KEY=""
OpenAI_API_KEY=""
UBERDUCK_API_KEY=""

[google_drive]
SIMILARITY=""
MOVIES_LIST=""
